name: Post to Socials

on:
  schedule:
    - cron: "30 6,17,22 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Use the latest Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Post to Socials
        run: python post_to_socials.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          FARCASTER_API_KEY: ${{ secrets.FARCASTER_API_KEY }}
          FARCASTER_SIGNER_UUID: ${{ secrets.FARCASTER_SIGNER_UUID }}
